### ISSUE TITLE
Update documentation for pre-requisites to include AWS support requirement

### ISSUE THREAD

**Issue by saltysoup** [FINRAOS/aphelion#18]
Exception being thrown by the limit scraping service when AWS Support is not enabled (I don't have it on my account). I think at least developer tier has to be enabled

```shell
bash-4.2# tail /var/log/cron.log 
Traceback (most recent call last):
  File "/opt/staging/limits.py", line 75, in <module>
    ta_resp = support.describe_trusted_advisor_check_result(checkId = 'eW7HH0l7J9', language='en')
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SubscriptionRequiredException) when calling the DescribeTrustedAdvisorCheckResult operation: AWS Premium Support Subscription is required to use this service.
```

(Pre-req page)[https://github.com/FINRAOS/aphelion/blob/master/docs/Local-Setup.md]

**Comment by kood1** [comment]
@saltysoup thanks for this.  We will make the change in the docs as well as website.
